package com.myspace.caleb;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class entrada implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String entrance;

	public entrada() {
	}

	public java.lang.String getEntrance() {
		return this.entrance;
	}

	public void setEntrance(java.lang.String entrance) {
		this.entrance = entrance;
	}

	public entrada(java.lang.String entrance) {
		this.entrance = entrance;
	}

}