package com.myspace.caleb;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class salida implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String reponse;

	public salida() {
	}

	public java.lang.String getReponse() {
		return this.reponse;
	}

	public void setReponse(java.lang.String reponse) {
		this.reponse = reponse;
	}

	public salida(java.lang.String reponse) {
		this.reponse = reponse;
	}

}